name: Ban Appeal
description: Create a report to appeal a ban from the JeriCraft Minecraft/Discord server.
title: "Ban Appeal for: <name>"
labels: [ "Ban Appeal" ]
assignees: Chalwk77
body:
  - type: markdown
    attributes:
      value: |
        **ðŸ“Œ Describe the reason for your ban**
        > Provide a clear and concise descriptions in the following sections.
        > Use headers (`#`) or lists (`-`) to organize your thoughts.
  - type: textarea
    id: why-should-we-unban-you
    attributes:
      label: ðŸ” Why should we unban you?
      description: Provide a clear and concise reason why you should be unbanned from the JeriCraft server.
      placeholder: "Write your reason here"
      value: "-"
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: ðŸ“ Additional context
      description: Write any other context or information about your ban appeal here.
      placeholder: "Further context or information here"
      value: "-"
    validations:
      required: true
  - type: textarea
    id: contact-info
    attributes:
      label: âœ”ï¸ Contact Information
      description: Provide your Discord and/or Minecraft Username.
      placeholder: "Discord and/or Minecraft Username: YourUsername"
      value: "-"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **ðŸ“· Screenshots**
        > Include any relevant screenshots to help illustrate your ban appeal.
        >
        >
        > ðŸ™Œ Thank you
        >
        > **We appreciate your effort in appealing your ban from the JeriCraft server. Your input is invaluable!**